<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- =============== Load Dependencies =============== -->
  <xacro:include filename="$(find torobo_resources)/urdf/common.xacro"/>

  <!-- =============== Constants =============== -->
    <xacro:property name="BASE_HEIGHT" value="0.785"/>
    <!--<xacro:property name="PI" value="3.14159"/>-->

  <!-- =============== Link & Joint =============== -->
  <xacro:macro name="base_v0" params="prefix parent *joint_origin">

    <joint name="${prefix}base_footprint_joint" type="fixed">
     <xacro:insert_block name="joint_origin"/>
        <parent link="${parent}"/>
      <child link="${prefix}base_footprint"/>
    </joint>
    <link name="${prefix}base_footprint"/>

    <joint name="${prefix}base_joint" type="fixed">
      <origin xyz="0 0 ${BASE_HEIGHT}"/>
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link"/>
    </joint>

    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="0.09" length="0.015"/>
        </geometry>
        <material name="white"/>
      </visual>

      <visual>
        <origin xyz="0 0 -${BASE_HEIGHT / 2.0}" />
        <geometry>
          <box size="0.10 0.10 ${BASE_HEIGHT}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="0.015" radius="0.09"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -${BASE_HEIGHT / 2.0}" />
        <geometry>
          <box size="0.10 0.10 ${BASE_HEIGHT}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="1"/>
        <inertia
          ixx="1" ixy="0" ixz="0"
          iyy="1" iyz="0" izz="1"/>
      </inertial>

      <visual>
        <geometry>
          <mesh filename="package://torobo_resources/meshes/base/STL/tatsushi/Bed_3.stl"/>
        </geometry>
        <origin xyz="0.2 -0.9 -0.785" rpy="0.0 0.0 ${radians(270)}"/>
        <material name="red">
          <color rgba="0.8 0.0 0.0 1.0"/>
        </material>
      </visual>

      <visual>
        <geometry>
          <mesh filename="package://torobo_resources/meshes/base/STL/tatsushi/Echo_3.stl"/>
        </geometry>
        <origin xyz="-0.2 1.0 -0.785" rpy="0.0 0.0 ${radians(270)}"/>
        <material name="green">
          <color rgba="0.0 0.8 0.0 1.0"/>
        </material>
      </visual>

      <!--<visual>
        <geometry>
          <mesh filename="package://torobo_resources/meshes/base/STL/tatsushi/Collision_3.stl"/>
        </geometry>
        <origin xyz="0.0 0.0 -0.785" rpy="0.0 0.0 0.0"/>
        <material name="Cyan">
          <color rgba="0.0 1.0 1.0 0.5"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <mesh filename="package://torobo_resources/meshes/base/STL/tatsushi/Collision_3.stl"/>
        </geometry>
        <origin xyz="0.0 0.0 -0.785" rpy="0.0 0.0 0.0"/>
        <material name="Cyan">
          <color rgba="0.0 1.0 1.0 0.5"/>
        </material>
      </collision>-->
    </link>

    <joint name="${prefix}base/joint_tip" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base/link_tip"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}base/link_tip"/>

  </xacro:macro>

</robot>
