<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- =============== Load Dependencies =============== -->
  <xacro:include filename="$(find torobo_resources)/urdf/common.xacro"/>

  <!-- =============== Constants =============== -->
  <xacro:property name="BASE_HEIGHT" value="0.785"/>

  <!-- =============== Link & Joint =============== -->
  <xacro:macro name="base_v0" params="prefix parent *joint_origin">

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <xacro:insert_block name="joint_origin"/>
      <parent link="${parent}"/>
      <child link="${prefix}base_footprint"/>
    </joint>
    <link name="${prefix}base_footprint"/>

    <joint name="${prefix}base_joint" type="fixed">
      <origin xyz="0 0 ${BASE_HEIGHT}"/>
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link"/>
    </joint>

    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="0.015" radius="0.09"/>
        </geometry>
        <material name="white"/>
      </visual>
      <visual>
        <origin xyz="0 0 -${BASE_HEIGHT / 2.0}" />
        <geometry>
          <box size="0.10 0.10 ${BASE_HEIGHT}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="0.015" radius="0.09"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -${BASE_HEIGHT / 2.0}" />
        <geometry>
          <box size="0.10 0.10 ${BASE_HEIGHT}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="1"/>
        <inertia
          ixx="1" ixy="0" ixz="0"
          iyy="1" iyz="0" izz="1"/>
      </inertial>
    </link>

    <joint name="${prefix}base/joint_tip" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base/link_tip"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}base/link_tip"/>

  </xacro:macro>

</robot>
