// Auto-generated. Do not edit!

// (in-package torobo_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveTeachingTrajectoryGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.teachingTrajectoryName = null;
    }
    else {
      if (initObj.hasOwnProperty('teachingTrajectoryName')) {
        this.teachingTrajectoryName = initObj.teachingTrajectoryName
      }
      else {
        this.teachingTrajectoryName = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveTeachingTrajectoryGoal
    // Serialize message field [teachingTrajectoryName]
    bufferOffset = _serializer.string(obj.teachingTrajectoryName, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveTeachingTrajectoryGoal
    let len;
    let data = new MoveTeachingTrajectoryGoal(null);
    // Deserialize message field [teachingTrajectoryName]
    data.teachingTrajectoryName = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.teachingTrajectoryName.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'torobo_msgs/MoveTeachingTrajectoryGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e69c8cdc2b83254a745638df8e512b10';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string teachingTrajectoryName
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveTeachingTrajectoryGoal(null);
    if (msg.teachingTrajectoryName !== undefined) {
      resolved.teachingTrajectoryName = msg.teachingTrajectoryName;
    }
    else {
      resolved.teachingTrajectoryName = ''
    }

    return resolved;
    }
};

module.exports = MoveTeachingTrajectoryGoal;
