arm_robot_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  gains:
    joint1: {p: 100, d: 10, i: 20, i_clamp: 1}
    joint2: {p: 80, d: 10, i: 20, i_clamp: 1}
    joint3: {p: 100, d: 10, i: 20, i_clamp: 1}
    joint4: {p: 100, d: 10, i: 20, i_clamp: 1}
    joint5: {p: 100, d: 10, i: 20, i_clamp: 1}
    joint6: {p: 100, d: 10, i: 20, i_clamp: 1}
    joint7: {p: 100, d: 10, i: 20, i_clamp: 1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
