# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

# Position Controllers ---------------------------------------
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  action_ns: follow_joint_trajectory  # for moveit
  action_type: FollowJointTrajectory  # for moveit (==>type)
  action_default: true                # for moveit (==>default)
  joints:
    - arm/joint_1
    - arm/joint_2
    - arm/joint_3
    - arm/joint_4
    - arm/joint_5
    - arm/joint_6
    - arm/joint_7
  allow_partial_joints_goal: true
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    arm/joint_1: {trajectory: 0.01745, goal: 0.01745}
    arm/joint_2: {trajectory: 0.01745, goal: 0.01745}
    arm/joint_3: {trajectory: 0.01745, goal: 0.01745}
    arm/joint_4: {trajectory: 0.01745, goal: 0.01745}
    arm/joint_5: {trajectory: 0.01745, goal: 0.01745}
    arm/joint_6: {trajectory: 0.01745, goal: 0.01745}
    arm/joint_7: {trajectory: 0.01745, goal: 0.01745}
  stop_trajectory_duration: 0.5
  state_publish_rate: 20
  action_monitor_rate: 20

gripper_controller:
  type: "position_controllers/ToroboGripperActionController"
  action_ns: gripper_cmd              # for moveit
  action_type: GripperCommand         # for moveit (==>type)
  action_default: true                # for moveit (==>default)
  joint: gripper/finger_joint
  goal_tolerance: 0.01
  stalled_velocity_threshold: 0.01
  stall_timeout: 0.2
  gains:
    gripper/finger_joint: {p: 200, d: 1, i: 5, i_clamp: 1}

