// Generated by gencpp from file torobo_msgs/CalculateData.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_CALCULATEDATA_H
#define TOROBO_MSGS_MESSAGE_CALCULATEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace torobo_msgs
{
template <class ContainerAllocator>
struct CalculateData_
{
  typedef CalculateData_<ContainerAllocator> Type;

  CalculateData_()
    : header()
    , CalculatedJointValue()  {
    }
  CalculateData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , CalculatedJointValue(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _CalculatedJointValue_type;
  _CalculatedJointValue_type CalculatedJointValue;





  typedef boost::shared_ptr< ::torobo_msgs::CalculateData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::CalculateData_<ContainerAllocator> const> ConstPtr;

}; // struct CalculateData_

typedef ::torobo_msgs::CalculateData_<std::allocator<void> > CalculateData;

typedef boost::shared_ptr< ::torobo_msgs::CalculateData > CalculateDataPtr;
typedef boost::shared_ptr< ::torobo_msgs::CalculateData const> CalculateDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::CalculateData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::CalculateData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::CalculateData_<ContainerAllocator1> & lhs, const ::torobo_msgs::CalculateData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.CalculatedJointValue == rhs.CalculatedJointValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::CalculateData_<ContainerAllocator1> & lhs, const ::torobo_msgs::CalculateData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::CalculateData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::CalculateData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::CalculateData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::CalculateData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::CalculateData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::CalculateData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::CalculateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbe3f603e6909e94b26707520c4cef74";
  }

  static const char* value(const ::torobo_msgs::CalculateData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbe3f603e6909e94ULL;
  static const uint64_t static_value2 = 0xb26707520c4cef74ULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::CalculateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/CalculateData";
  }

  static const char* value(const ::torobo_msgs::CalculateData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::CalculateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64[] CalculatedJointValue\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::torobo_msgs::CalculateData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::CalculateData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.CalculatedJointValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalculateData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::CalculateData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::CalculateData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "CalculatedJointValue[]" << std::endl;
    for (size_t i = 0; i < v.CalculatedJointValue.size(); ++i)
    {
      s << indent << "  CalculatedJointValue[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.CalculatedJointValue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_CALCULATEDATA_H
