// Generated by gencpp from file torobo_msgs/CancelTrajectory.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_CANCELTRAJECTORY_H
#define TOROBO_MSGS_MESSAGE_CANCELTRAJECTORY_H

#include <ros/service_traits.h>


#include <torobo_msgs/CancelTrajectoryRequest.h>
#include <torobo_msgs/CancelTrajectoryResponse.h>


namespace torobo_msgs
{

struct CancelTrajectory
{

typedef CancelTrajectoryRequest Request;
typedef CancelTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CancelTrajectory
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::CancelTrajectory > {
  static const char* value()
  {
    return "abb91c83ed030d595b2e5754d356a7f3";
  }

  static const char* value(const ::torobo_msgs::CancelTrajectory&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::CancelTrajectory > {
  static const char* value()
  {
    return "torobo_msgs/CancelTrajectory";
  }

  static const char* value(const ::torobo_msgs::CancelTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::CancelTrajectoryRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::CancelTrajectory >
template<>
struct MD5Sum< ::torobo_msgs::CancelTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::CancelTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::CancelTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::CancelTrajectoryRequest> should match
// service_traits::DataType< ::torobo_msgs::CancelTrajectory >
template<>
struct DataType< ::torobo_msgs::CancelTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::CancelTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::CancelTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::CancelTrajectoryResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::CancelTrajectory >
template<>
struct MD5Sum< ::torobo_msgs::CancelTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::CancelTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::CancelTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::CancelTrajectoryResponse> should match
// service_traits::DataType< ::torobo_msgs::CancelTrajectory >
template<>
struct DataType< ::torobo_msgs::CancelTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::CancelTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::CancelTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_CANCELTRAJECTORY_H
