// Generated by gencpp from file torobo_msgs/CheckCollisionResponse.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_CHECKCOLLISIONRESPONSE_H
#define TOROBO_MSGS_MESSAGE_CHECKCOLLISIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace torobo_msgs
{
template <class ContainerAllocator>
struct CheckCollisionResponse_
{
  typedef CheckCollisionResponse_<ContainerAllocator> Type;

  CheckCollisionResponse_()
    : isColliding(false)  {
    }
  CheckCollisionResponse_(const ContainerAllocator& _alloc)
    : isColliding(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isColliding_type;
  _isColliding_type isColliding;





  typedef boost::shared_ptr< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckCollisionResponse_

typedef ::torobo_msgs::CheckCollisionResponse_<std::allocator<void> > CheckCollisionResponse;

typedef boost::shared_ptr< ::torobo_msgs::CheckCollisionResponse > CheckCollisionResponsePtr;
typedef boost::shared_ptr< ::torobo_msgs::CheckCollisionResponse const> CheckCollisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isColliding == rhs.isColliding;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b2cb34f17a03d15f695e88eb1712876";
  }

  static const char* value(const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b2cb34f17a03d15ULL;
  static const uint64_t static_value2 = 0xf695e88eb1712876ULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/CheckCollisionResponse";
  }

  static const char* value(const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isColliding\n"
"\n"
;
  }

  static const char* value(const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isColliding);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckCollisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::CheckCollisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "isColliding: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isColliding);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_CHECKCOLLISIONRESPONSE_H
