// Generated by gencpp from file torobo_msgs/ClearTrajectory.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_CLEARTRAJECTORY_H
#define TOROBO_MSGS_MESSAGE_CLEARTRAJECTORY_H

#include <ros/service_traits.h>


#include <torobo_msgs/ClearTrajectoryRequest.h>
#include <torobo_msgs/ClearTrajectoryResponse.h>


namespace torobo_msgs
{

struct ClearTrajectory
{

typedef ClearTrajectoryRequest Request;
typedef ClearTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearTrajectory
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::ClearTrajectory > {
  static const char* value()
  {
    return "abb91c83ed030d595b2e5754d356a7f3";
  }

  static const char* value(const ::torobo_msgs::ClearTrajectory&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::ClearTrajectory > {
  static const char* value()
  {
    return "torobo_msgs/ClearTrajectory";
  }

  static const char* value(const ::torobo_msgs::ClearTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::ClearTrajectoryRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::ClearTrajectory >
template<>
struct MD5Sum< ::torobo_msgs::ClearTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::ClearTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::ClearTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::ClearTrajectoryRequest> should match
// service_traits::DataType< ::torobo_msgs::ClearTrajectory >
template<>
struct DataType< ::torobo_msgs::ClearTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::ClearTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::ClearTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::ClearTrajectoryResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::ClearTrajectory >
template<>
struct MD5Sum< ::torobo_msgs::ClearTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::ClearTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::ClearTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::ClearTrajectoryResponse> should match
// service_traits::DataType< ::torobo_msgs::ClearTrajectory >
template<>
struct DataType< ::torobo_msgs::ClearTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::ClearTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::ClearTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_CLEARTRAJECTORY_H
