// Generated by gencpp from file torobo_msgs/ControllData.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_CONTROLLDATA_H
#define TOROBO_MSGS_MESSAGE_CONTROLLDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace torobo_msgs
{
template <class ContainerAllocator>
struct ControllData_
{
  typedef ControllData_<ContainerAllocator> Type;

  ControllData_()
    : header()
    , OriginalJointValue()
    , RealsenseDepth(0.0)  {
    }
  ControllData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , OriginalJointValue(_alloc)
    , RealsenseDepth(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _OriginalJointValue_type;
  _OriginalJointValue_type OriginalJointValue;

   typedef double _RealsenseDepth_type;
  _RealsenseDepth_type RealsenseDepth;





  typedef boost::shared_ptr< ::torobo_msgs::ControllData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::ControllData_<ContainerAllocator> const> ConstPtr;

}; // struct ControllData_

typedef ::torobo_msgs::ControllData_<std::allocator<void> > ControllData;

typedef boost::shared_ptr< ::torobo_msgs::ControllData > ControllDataPtr;
typedef boost::shared_ptr< ::torobo_msgs::ControllData const> ControllDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::ControllData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::ControllData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::ControllData_<ContainerAllocator1> & lhs, const ::torobo_msgs::ControllData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.OriginalJointValue == rhs.OriginalJointValue &&
    lhs.RealsenseDepth == rhs.RealsenseDepth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::ControllData_<ContainerAllocator1> & lhs, const ::torobo_msgs::ControllData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::ControllData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::ControllData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::ControllData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::ControllData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::ControllData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::ControllData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::ControllData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc555df7797f83d8d79097c136b37e1f";
  }

  static const char* value(const ::torobo_msgs::ControllData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc555df7797f83d8ULL;
  static const uint64_t static_value2 = 0xd79097c136b37e1fULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::ControllData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/ControllData";
  }

  static const char* value(const ::torobo_msgs::ControllData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::ControllData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64[] OriginalJointValue\n"
"float64 RealsenseDepth\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::torobo_msgs::ControllData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::ControllData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.OriginalJointValue);
      stream.next(m.RealsenseDepth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::ControllData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::ControllData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "OriginalJointValue[]" << std::endl;
    for (size_t i = 0; i < v.OriginalJointValue.size(); ++i)
    {
      s << indent << "  OriginalJointValue[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.OriginalJointValue[i]);
    }
    s << indent << "RealsenseDepth: ";
    Printer<double>::stream(s, indent + "  ", v.RealsenseDepth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_CONTROLLDATA_H
