// Generated by gencpp from file torobo_msgs/DeleteTeachingPoint.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_DELETETEACHINGPOINT_H
#define TOROBO_MSGS_MESSAGE_DELETETEACHINGPOINT_H

#include <ros/service_traits.h>


#include <torobo_msgs/DeleteTeachingPointRequest.h>
#include <torobo_msgs/DeleteTeachingPointResponse.h>


namespace torobo_msgs
{

struct DeleteTeachingPoint
{

typedef DeleteTeachingPointRequest Request;
typedef DeleteTeachingPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteTeachingPoint
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::DeleteTeachingPoint > {
  static const char* value()
  {
    return "a2c869ed0a6122eb036ee623c16fb042";
  }

  static const char* value(const ::torobo_msgs::DeleteTeachingPoint&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::DeleteTeachingPoint > {
  static const char* value()
  {
    return "torobo_msgs/DeleteTeachingPoint";
  }

  static const char* value(const ::torobo_msgs::DeleteTeachingPoint&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::DeleteTeachingPointRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::DeleteTeachingPoint >
template<>
struct MD5Sum< ::torobo_msgs::DeleteTeachingPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::DeleteTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::DeleteTeachingPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::DeleteTeachingPointRequest> should match
// service_traits::DataType< ::torobo_msgs::DeleteTeachingPoint >
template<>
struct DataType< ::torobo_msgs::DeleteTeachingPointRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::DeleteTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::DeleteTeachingPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::DeleteTeachingPointResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::DeleteTeachingPoint >
template<>
struct MD5Sum< ::torobo_msgs::DeleteTeachingPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::DeleteTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::DeleteTeachingPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::DeleteTeachingPointResponse> should match
// service_traits::DataType< ::torobo_msgs::DeleteTeachingPoint >
template<>
struct DataType< ::torobo_msgs::DeleteTeachingPointResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::DeleteTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::DeleteTeachingPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_DELETETEACHINGPOINT_H
