// Generated by gencpp from file torobo_msgs/GetCollisionInfo.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETCOLLISIONINFO_H
#define TOROBO_MSGS_MESSAGE_GETCOLLISIONINFO_H

#include <ros/service_traits.h>


#include <torobo_msgs/GetCollisionInfoRequest.h>
#include <torobo_msgs/GetCollisionInfoResponse.h>


namespace torobo_msgs
{

struct GetCollisionInfo
{

typedef GetCollisionInfoRequest Request;
typedef GetCollisionInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCollisionInfo
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::GetCollisionInfo > {
  static const char* value()
  {
    return "f0626346887ec50a585aed5a146d00dc";
  }

  static const char* value(const ::torobo_msgs::GetCollisionInfo&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::GetCollisionInfo > {
  static const char* value()
  {
    return "torobo_msgs/GetCollisionInfo";
  }

  static const char* value(const ::torobo_msgs::GetCollisionInfo&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::GetCollisionInfoRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::GetCollisionInfo >
template<>
struct MD5Sum< ::torobo_msgs::GetCollisionInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetCollisionInfo >::value();
  }
  static const char* value(const ::torobo_msgs::GetCollisionInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetCollisionInfoRequest> should match
// service_traits::DataType< ::torobo_msgs::GetCollisionInfo >
template<>
struct DataType< ::torobo_msgs::GetCollisionInfoRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetCollisionInfo >::value();
  }
  static const char* value(const ::torobo_msgs::GetCollisionInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::GetCollisionInfoResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::GetCollisionInfo >
template<>
struct MD5Sum< ::torobo_msgs::GetCollisionInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetCollisionInfo >::value();
  }
  static const char* value(const ::torobo_msgs::GetCollisionInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetCollisionInfoResponse> should match
// service_traits::DataType< ::torobo_msgs::GetCollisionInfo >
template<>
struct DataType< ::torobo_msgs::GetCollisionInfoResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetCollisionInfo >::value();
  }
  static const char* value(const ::torobo_msgs::GetCollisionInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETCOLLISIONINFO_H
