// Generated by gencpp from file torobo_msgs/GetCollisionInfoRequest.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETCOLLISIONINFOREQUEST_H
#define TOROBO_MSGS_MESSAGE_GETCOLLISIONINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <torobo_msgs/CollisionInfoRequest.h>

namespace torobo_msgs
{
template <class ContainerAllocator>
struct GetCollisionInfoRequest_
{
  typedef GetCollisionInfoRequest_<ContainerAllocator> Type;

  GetCollisionInfoRequest_()
    : collision_info_request()  {
    }
  GetCollisionInfoRequest_(const ContainerAllocator& _alloc)
    : collision_info_request(_alloc)  {
  (void)_alloc;
    }



   typedef  ::torobo_msgs::CollisionInfoRequest_<ContainerAllocator>  _collision_info_request_type;
  _collision_info_request_type collision_info_request;





  typedef boost::shared_ptr< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCollisionInfoRequest_

typedef ::torobo_msgs::GetCollisionInfoRequest_<std::allocator<void> > GetCollisionInfoRequest;

typedef boost::shared_ptr< ::torobo_msgs::GetCollisionInfoRequest > GetCollisionInfoRequestPtr;
typedef boost::shared_ptr< ::torobo_msgs::GetCollisionInfoRequest const> GetCollisionInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.collision_info_request == rhs.collision_info_request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c857681b40404a7551c566ca63b69e0";
  }

  static const char* value(const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c857681b40404a7ULL;
  static const uint64_t static_value2 = 0x551c566ca63b69e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/GetCollisionInfoRequest";
  }

  static const char* value(const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CollisionInfoRequest collision_info_request\n"
"\n"
"================================================================================\n"
"MSG: torobo_msgs/CollisionInfoRequest\n"
"sensor_msgs/JointState jointState\n"
"uint32 max_contacts\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collision_info_request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCollisionInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::GetCollisionInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "collision_info_request: ";
    s << std::endl;
    Printer< ::torobo_msgs::CollisionInfoRequest_<ContainerAllocator> >::stream(s, indent + "  ", v.collision_info_request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETCOLLISIONINFOREQUEST_H
