// Generated by gencpp from file torobo_msgs/GetServoState.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETSERVOSTATE_H
#define TOROBO_MSGS_MESSAGE_GETSERVOSTATE_H

#include <ros/service_traits.h>


#include <torobo_msgs/GetServoStateRequest.h>
#include <torobo_msgs/GetServoStateResponse.h>


namespace torobo_msgs
{

struct GetServoState
{

typedef GetServoStateRequest Request;
typedef GetServoStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetServoState
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::GetServoState > {
  static const char* value()
  {
    return "97bcac43fb1f87b145f4ed8da59438f9";
  }

  static const char* value(const ::torobo_msgs::GetServoState&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::GetServoState > {
  static const char* value()
  {
    return "torobo_msgs/GetServoState";
  }

  static const char* value(const ::torobo_msgs::GetServoState&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::GetServoStateRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::GetServoState >
template<>
struct MD5Sum< ::torobo_msgs::GetServoStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetServoState >::value();
  }
  static const char* value(const ::torobo_msgs::GetServoStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetServoStateRequest> should match
// service_traits::DataType< ::torobo_msgs::GetServoState >
template<>
struct DataType< ::torobo_msgs::GetServoStateRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetServoState >::value();
  }
  static const char* value(const ::torobo_msgs::GetServoStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::GetServoStateResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::GetServoState >
template<>
struct MD5Sum< ::torobo_msgs::GetServoStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetServoState >::value();
  }
  static const char* value(const ::torobo_msgs::GetServoStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetServoStateResponse> should match
// service_traits::DataType< ::torobo_msgs::GetServoState >
template<>
struct DataType< ::torobo_msgs::GetServoStateResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetServoState >::value();
  }
  static const char* value(const ::torobo_msgs::GetServoStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETSERVOSTATE_H
