// Generated by gencpp from file torobo_msgs/GetTeachingPointNames.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTNAMES_H
#define TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTNAMES_H

#include <ros/service_traits.h>


#include <torobo_msgs/GetTeachingPointNamesRequest.h>
#include <torobo_msgs/GetTeachingPointNamesResponse.h>


namespace torobo_msgs
{

struct GetTeachingPointNames
{

typedef GetTeachingPointNamesRequest Request;
typedef GetTeachingPointNamesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTeachingPointNames
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::GetTeachingPointNames > {
  static const char* value()
  {
    return "86750bf3b770c5fb06c0dead2089ecbf";
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointNames&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::GetTeachingPointNames > {
  static const char* value()
  {
    return "torobo_msgs/GetTeachingPointNames";
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointNames&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::GetTeachingPointNamesRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::GetTeachingPointNames >
template<>
struct MD5Sum< ::torobo_msgs::GetTeachingPointNamesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetTeachingPointNames >::value();
  }
  static const char* value(const ::torobo_msgs::GetTeachingPointNamesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetTeachingPointNamesRequest> should match
// service_traits::DataType< ::torobo_msgs::GetTeachingPointNames >
template<>
struct DataType< ::torobo_msgs::GetTeachingPointNamesRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetTeachingPointNames >::value();
  }
  static const char* value(const ::torobo_msgs::GetTeachingPointNamesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::GetTeachingPointNamesResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::GetTeachingPointNames >
template<>
struct MD5Sum< ::torobo_msgs::GetTeachingPointNamesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetTeachingPointNames >::value();
  }
  static const char* value(const ::torobo_msgs::GetTeachingPointNamesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetTeachingPointNamesResponse> should match
// service_traits::DataType< ::torobo_msgs::GetTeachingPointNames >
template<>
struct DataType< ::torobo_msgs::GetTeachingPointNamesResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetTeachingPointNames >::value();
  }
  static const char* value(const ::torobo_msgs::GetTeachingPointNamesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTNAMES_H
