// Generated by gencpp from file torobo_msgs/GetTeachingTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETTEACHINGTRAJECTORYRESPONSE_H
#define TOROBO_MSGS_MESSAGE_GETTEACHINGTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace torobo_msgs
{
template <class ContainerAllocator>
struct GetTeachingTrajectoryResponse_
{
  typedef GetTeachingTrajectoryResponse_<ContainerAllocator> Type;

  GetTeachingTrajectoryResponse_()
    : success(false)
    , trajectory()  {
    }
  GetTeachingTrajectoryResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;





  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTeachingTrajectoryResponse_

typedef ::torobo_msgs::GetTeachingTrajectoryResponse_<std::allocator<void> > GetTeachingTrajectoryResponse;

typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryResponse > GetTeachingTrajectoryResponsePtr;
typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryResponse const> GetTeachingTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.trajectory == rhs.trajectory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dac17c68dbaa65fdf53974580600f37";
  }

  static const char* value(const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dac17c68dbaa65fULL;
  static const uint64_t static_value2 = 0xdf53974580600f37ULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/GetTeachingTrajectoryResponse";
  }

  static const char* value(const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"trajectory_msgs/JointTrajectory trajectory\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTeachingTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::GetTeachingTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETTEACHINGTRAJECTORYRESPONSE_H
