// Generated by gencpp from file torobo_msgs/GetTeachingPointResponse.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTRESPONSE_H
#define TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectoryPoint.h>

namespace torobo_msgs
{
template <class ContainerAllocator>
struct GetTeachingPointResponse_
{
  typedef GetTeachingPointResponse_<ContainerAllocator> Type;

  GetTeachingPointResponse_()
    : success(false)
    , point()  {
    }
  GetTeachingPointResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTeachingPointResponse_

typedef ::torobo_msgs::GetTeachingPointResponse_<std::allocator<void> > GetTeachingPointResponse;

typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointResponse > GetTeachingPointResponsePtr;
typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointResponse const> GetTeachingPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4fb311969de1088a6325a18d60fc769";
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4fb311969de1088ULL;
  static const uint64_t static_value2 = 0xa6325a18d60fc769ULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/GetTeachingPointResponse";
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"trajectory_msgs/JointTrajectoryPoint point\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTeachingPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::GetTeachingPointResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTRESPONSE_H
