// Generated by gencpp from file torobo_msgs/GetToroboJointState.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETTOROBOJOINTSTATE_H
#define TOROBO_MSGS_MESSAGE_GETTOROBOJOINTSTATE_H

#include <ros/service_traits.h>


#include <torobo_msgs/GetToroboJointStateRequest.h>
#include <torobo_msgs/GetToroboJointStateResponse.h>


namespace torobo_msgs
{

struct GetToroboJointState
{

typedef GetToroboJointStateRequest Request;
typedef GetToroboJointStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetToroboJointState
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::GetToroboJointState > {
  static const char* value()
  {
    return "f076a05b5c866f51043035790c9b9bbf";
  }

  static const char* value(const ::torobo_msgs::GetToroboJointState&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::GetToroboJointState > {
  static const char* value()
  {
    return "torobo_msgs/GetToroboJointState";
  }

  static const char* value(const ::torobo_msgs::GetToroboJointState&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::GetToroboJointStateRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::GetToroboJointState >
template<>
struct MD5Sum< ::torobo_msgs::GetToroboJointStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetToroboJointState >::value();
  }
  static const char* value(const ::torobo_msgs::GetToroboJointStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetToroboJointStateRequest> should match
// service_traits::DataType< ::torobo_msgs::GetToroboJointState >
template<>
struct DataType< ::torobo_msgs::GetToroboJointStateRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetToroboJointState >::value();
  }
  static const char* value(const ::torobo_msgs::GetToroboJointStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::GetToroboJointStateResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::GetToroboJointState >
template<>
struct MD5Sum< ::torobo_msgs::GetToroboJointStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::GetToroboJointState >::value();
  }
  static const char* value(const ::torobo_msgs::GetToroboJointStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::GetToroboJointStateResponse> should match
// service_traits::DataType< ::torobo_msgs::GetToroboJointState >
template<>
struct DataType< ::torobo_msgs::GetToroboJointStateResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::GetToroboJointState >::value();
  }
  static const char* value(const ::torobo_msgs::GetToroboJointStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETTOROBOJOINTSTATE_H
