// Generated by gencpp from file torobo_msgs/GetTeachingPointRequest.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTREQUEST_H
#define TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace torobo_msgs
{
template <class ContainerAllocator>
struct GetTeachingPointRequest_
{
  typedef GetTeachingPointRequest_<ContainerAllocator> Type;

  GetTeachingPointRequest_()
    : teachingPointName()  {
    }
  GetTeachingPointRequest_(const ContainerAllocator& _alloc)
    : teachingPointName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _teachingPointName_type;
  _teachingPointName_type teachingPointName;





  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTeachingPointRequest_

typedef ::torobo_msgs::GetTeachingPointRequest_<std::allocator<void> > GetTeachingPointRequest;

typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointRequest > GetTeachingPointRequestPtr;
typedef boost::shared_ptr< ::torobo_msgs::GetTeachingPointRequest const> GetTeachingPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.teachingPointName == rhs.teachingPointName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b30b123766e92f0219af2be4ff0319f";
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b30b123766e92f0ULL;
  static const uint64_t static_value2 = 0x219af2be4ff0319fULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/GetTeachingPointRequest";
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string teachingPointName \n"
;
  }

  static const char* value(const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.teachingPointName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTeachingPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::GetTeachingPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "teachingPointName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.teachingPointName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETTEACHINGPOINTREQUEST_H
