// Generated by gencpp from file torobo_msgs/GetToroboJointStateRequest.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETTOROBOJOINTSTATEREQUEST_H
#define TOROBO_MSGS_MESSAGE_GETTOROBOJOINTSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace torobo_msgs
{
template <class ContainerAllocator>
struct GetToroboJointStateRequest_
{
  typedef GetToroboJointStateRequest_<ContainerAllocator> Type;

  GetToroboJointStateRequest_()
    : controllerName()  {
    }
  GetToroboJointStateRequest_(const ContainerAllocator& _alloc)
    : controllerName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _controllerName_type;
  _controllerName_type controllerName;





  typedef boost::shared_ptr< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetToroboJointStateRequest_

typedef ::torobo_msgs::GetToroboJointStateRequest_<std::allocator<void> > GetToroboJointStateRequest;

typedef boost::shared_ptr< ::torobo_msgs::GetToroboJointStateRequest > GetToroboJointStateRequestPtr;
typedef boost::shared_ptr< ::torobo_msgs::GetToroboJointStateRequest const> GetToroboJointStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.controllerName == rhs.controllerName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "871c8bc8e290d38ba0b734d07fbebbf8";
  }

  static const char* value(const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x871c8bc8e290d38bULL;
  static const uint64_t static_value2 = 0xa0b734d07fbebbf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/GetToroboJointStateRequest";
  }

  static const char* value(const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string controllerName\n"
;
  }

  static const char* value(const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controllerName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetToroboJointStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::GetToroboJointStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "controllerName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.controllerName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETTOROBOJOINTSTATEREQUEST_H
