// Generated by gencpp from file torobo_msgs/GetTeachingTrajectoryNamesResponse.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_GETTEACHINGTRAJECTORYNAMESRESPONSE_H
#define TOROBO_MSGS_MESSAGE_GETTEACHINGTRAJECTORYNAMESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace torobo_msgs
{
template <class ContainerAllocator>
struct GetTeachingTrajectoryNamesResponse_
{
  typedef GetTeachingTrajectoryNamesResponse_<ContainerAllocator> Type;

  GetTeachingTrajectoryNamesResponse_()
    : success(false)
    , teachingTrajectoryNames()  {
    }
  GetTeachingTrajectoryNamesResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , teachingTrajectoryNames(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _teachingTrajectoryNames_type;
  _teachingTrajectoryNames_type teachingTrajectoryNames;





  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTeachingTrajectoryNamesResponse_

typedef ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<std::allocator<void> > GetTeachingTrajectoryNamesResponse;

typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryNamesResponse > GetTeachingTrajectoryNamesResponsePtr;
typedef boost::shared_ptr< ::torobo_msgs::GetTeachingTrajectoryNamesResponse const> GetTeachingTrajectoryNamesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.teachingTrajectoryNames == rhs.teachingTrajectoryNames;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator1> & lhs, const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b78c8a970090dfff436e75670b29785b";
  }

  static const char* value(const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb78c8a970090dfffULL;
  static const uint64_t static_value2 = 0x436e75670b29785bULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/GetTeachingTrajectoryNamesResponse";
  }

  static const char* value(const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string[] teachingTrajectoryNames\n"
;
  }

  static const char* value(const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.teachingTrajectoryNames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTeachingTrajectoryNamesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::GetTeachingTrajectoryNamesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "teachingTrajectoryNames[]" << std::endl;
    for (size_t i = 0; i < v.teachingTrajectoryNames.size(); ++i)
    {
      s << indent << "  teachingTrajectoryNames[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.teachingTrajectoryNames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_GETTEACHINGTRAJECTORYNAMESRESPONSE_H
