// Generated by gencpp from file torobo_msgs/MoveHomePositionResult.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_MOVEHOMEPOSITIONRESULT_H
#define TOROBO_MSGS_MESSAGE_MOVEHOMEPOSITIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace torobo_msgs
{
template <class ContainerAllocator>
struct MoveHomePositionResult_
{
  typedef MoveHomePositionResult_<ContainerAllocator> Type;

  MoveHomePositionResult_()
    : errorCode(0)
    , jointState()  {
    }
  MoveHomePositionResult_(const ContainerAllocator& _alloc)
    : errorCode(0)
    , jointState(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _errorCode_type;
  _errorCode_type errorCode;

   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _jointState_type;
  _jointState_type jointState;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SUCCESSFUL)
  #undef SUCCESSFUL
#endif
#if defined(_WIN32) && defined(FAILURE)
  #undef FAILURE
#endif
#if defined(_WIN32) && defined(PREEMPTED)
  #undef PREEMPTED
#endif

  enum {
    SUCCESSFUL = 0,
    FAILURE = -1,
    PREEMPTED = -2,
  };


  typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveHomePositionResult_

typedef ::torobo_msgs::MoveHomePositionResult_<std::allocator<void> > MoveHomePositionResult;

typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionResult > MoveHomePositionResultPtr;
typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionResult const> MoveHomePositionResultConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator1> & lhs, const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator2> & rhs)
{
  return lhs.errorCode == rhs.errorCode &&
    lhs.jointState == rhs.jointState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator1> & lhs, const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5af78d1aaab840aeb31f007340c79c5c";
  }

  static const char* value(const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5af78d1aaab840aeULL;
  static const uint64_t static_value2 = 0xb31f007340c79c5cULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/MoveHomePositionResult";
  }

  static const char* value(const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"int32 errorCode\n"
"int32 SUCCESSFUL = 0\n"
"int32 FAILURE = -1\n"
"int32 PREEMPTED = -2\n"
"sensor_msgs/JointState jointState\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.errorCode);
      stream.next(m.jointState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveHomePositionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::MoveHomePositionResult_<ContainerAllocator>& v)
  {
    s << indent << "errorCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.errorCode);
    s << indent << "jointState: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.jointState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_MOVEHOMEPOSITIONRESULT_H
