// Generated by gencpp from file torobo_msgs/MoveHomePositionFeedback.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_MOVEHOMEPOSITIONFEEDBACK_H
#define TOROBO_MSGS_MESSAGE_MOVEHOMEPOSITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectoryPoint.h>

namespace torobo_msgs
{
template <class ContainerAllocator>
struct MoveHomePositionFeedback_
{
  typedef MoveHomePositionFeedback_<ContainerAllocator> Type;

  MoveHomePositionFeedback_()
    : actual()  {
    }
  MoveHomePositionFeedback_(const ContainerAllocator& _alloc)
    : actual(_alloc)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _actual_type;
  _actual_type actual;





  typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveHomePositionFeedback_

typedef ::torobo_msgs::MoveHomePositionFeedback_<std::allocator<void> > MoveHomePositionFeedback;

typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionFeedback > MoveHomePositionFeedbackPtr;
typedef boost::shared_ptr< ::torobo_msgs::MoveHomePositionFeedback const> MoveHomePositionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator1> & lhs, const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.actual == rhs.actual;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator1> & lhs, const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "473828e1b0881c8cb007ca255949f320";
  }

  static const char* value(const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x473828e1b0881c8cULL;
  static const uint64_t static_value2 = 0xb007ca255949f320ULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/MoveHomePositionFeedback";
  }

  static const char* value(const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"trajectory_msgs/JointTrajectoryPoint actual\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actual);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveHomePositionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::MoveHomePositionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "actual: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.actual);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_MOVEHOMEPOSITIONFEEDBACK_H
