// Generated by gencpp from file torobo_msgs/RecordTeachingPoint.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_RECORDTEACHINGPOINT_H
#define TOROBO_MSGS_MESSAGE_RECORDTEACHINGPOINT_H

#include <ros/service_traits.h>


#include <torobo_msgs/RecordTeachingPointRequest.h>
#include <torobo_msgs/RecordTeachingPointResponse.h>


namespace torobo_msgs
{

struct RecordTeachingPoint
{

typedef RecordTeachingPointRequest Request;
typedef RecordTeachingPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecordTeachingPoint
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::RecordTeachingPoint > {
  static const char* value()
  {
    return "da402d8c24b24843426eaf136284c37e";
  }

  static const char* value(const ::torobo_msgs::RecordTeachingPoint&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::RecordTeachingPoint > {
  static const char* value()
  {
    return "torobo_msgs/RecordTeachingPoint";
  }

  static const char* value(const ::torobo_msgs::RecordTeachingPoint&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingPointRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingPoint >
template<>
struct MD5Sum< ::torobo_msgs::RecordTeachingPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::RecordTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::RecordTeachingPointRequest> should match
// service_traits::DataType< ::torobo_msgs::RecordTeachingPoint >
template<>
struct DataType< ::torobo_msgs::RecordTeachingPointRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::RecordTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingPointResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingPoint >
template<>
struct MD5Sum< ::torobo_msgs::RecordTeachingPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::RecordTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::RecordTeachingPointResponse> should match
// service_traits::DataType< ::torobo_msgs::RecordTeachingPoint >
template<>
struct DataType< ::torobo_msgs::RecordTeachingPointResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::RecordTeachingPoint >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_RECORDTEACHINGPOINT_H
