// Generated by gencpp from file torobo_msgs/RecordTeachingTrajectory.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_RECORDTEACHINGTRAJECTORY_H
#define TOROBO_MSGS_MESSAGE_RECORDTEACHINGTRAJECTORY_H

#include <ros/service_traits.h>


#include <torobo_msgs/RecordTeachingTrajectoryRequest.h>
#include <torobo_msgs/RecordTeachingTrajectoryResponse.h>


namespace torobo_msgs
{

struct RecordTeachingTrajectory
{

typedef RecordTeachingTrajectoryRequest Request;
typedef RecordTeachingTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecordTeachingTrajectory
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::RecordTeachingTrajectory > {
  static const char* value()
  {
    return "c669b47b2c67251a736ac9c2f832189a";
  }

  static const char* value(const ::torobo_msgs::RecordTeachingTrajectory&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::RecordTeachingTrajectory > {
  static const char* value()
  {
    return "torobo_msgs/RecordTeachingTrajectory";
  }

  static const char* value(const ::torobo_msgs::RecordTeachingTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingTrajectoryRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingTrajectory >
template<>
struct MD5Sum< ::torobo_msgs::RecordTeachingTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::RecordTeachingTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::RecordTeachingTrajectoryRequest> should match
// service_traits::DataType< ::torobo_msgs::RecordTeachingTrajectory >
template<>
struct DataType< ::torobo_msgs::RecordTeachingTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::RecordTeachingTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingTrajectoryResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::RecordTeachingTrajectory >
template<>
struct MD5Sum< ::torobo_msgs::RecordTeachingTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::RecordTeachingTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::RecordTeachingTrajectoryResponse> should match
// service_traits::DataType< ::torobo_msgs::RecordTeachingTrajectory >
template<>
struct DataType< ::torobo_msgs::RecordTeachingTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::RecordTeachingTrajectory >::value();
  }
  static const char* value(const ::torobo_msgs::RecordTeachingTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_RECORDTEACHINGTRAJECTORY_H
