// Generated by gencpp from file torobo_msgs/SetControlModeRequest.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_SETCONTROLMODEREQUEST_H
#define TOROBO_MSGS_MESSAGE_SETCONTROLMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace torobo_msgs
{
template <class ContainerAllocator>
struct SetControlModeRequest_
{
  typedef SetControlModeRequest_<ContainerAllocator> Type;

  SetControlModeRequest_()
    : control_mode_name()
    , joint_names()  {
    }
  SetControlModeRequest_(const ContainerAllocator& _alloc)
    : control_mode_name(_alloc)
    , joint_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _control_mode_name_type;
  _control_mode_name_type control_mode_name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;





  typedef boost::shared_ptr< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetControlModeRequest_

typedef ::torobo_msgs::SetControlModeRequest_<std::allocator<void> > SetControlModeRequest;

typedef boost::shared_ptr< ::torobo_msgs::SetControlModeRequest > SetControlModeRequestPtr;
typedef boost::shared_ptr< ::torobo_msgs::SetControlModeRequest const> SetControlModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.control_mode_name == rhs.control_mode_name &&
    lhs.joint_names == rhs.joint_names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator1> & lhs, const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f814b0aab737eeeac0af8445ba77ae6b";
  }

  static const char* value(const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf814b0aab737eeeaULL;
  static const uint64_t static_value2 = 0xc0af8445ba77ae6bULL;
};

template<class ContainerAllocator>
struct DataType< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torobo_msgs/SetControlModeRequest";
  }

  static const char* value(const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# available control_mode_name\n"
"# \"position\" : Position control mode\n"
"# \"velocity\" : Velocity control mode\n"
"# \"current\" : Current control mode\n"
"# \"external_force_following\" : External force following control mode\n"
"string control_mode_name\n"
"string[] joint_names\n"
;
  }

  static const char* value(const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode_name);
      stream.next(m.joint_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetControlModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torobo_msgs::SetControlModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torobo_msgs::SetControlModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "control_mode_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.control_mode_name);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_SETCONTROLMODEREQUEST_H
