// Generated by gencpp from file torobo_msgs/SetRobotControllerParameter.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_SETROBOTCONTROLLERPARAMETER_H
#define TOROBO_MSGS_MESSAGE_SETROBOTCONTROLLERPARAMETER_H

#include <ros/service_traits.h>


#include <torobo_msgs/SetRobotControllerParameterRequest.h>
#include <torobo_msgs/SetRobotControllerParameterResponse.h>


namespace torobo_msgs
{

struct SetRobotControllerParameter
{

typedef SetRobotControllerParameterRequest Request;
typedef SetRobotControllerParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobotControllerParameter
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::SetRobotControllerParameter > {
  static const char* value()
  {
    return "f6a7b3b84aaf90a78da4f4ecdbe454b7";
  }

  static const char* value(const ::torobo_msgs::SetRobotControllerParameter&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::SetRobotControllerParameter > {
  static const char* value()
  {
    return "torobo_msgs/SetRobotControllerParameter";
  }

  static const char* value(const ::torobo_msgs::SetRobotControllerParameter&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::SetRobotControllerParameterRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::SetRobotControllerParameter >
template<>
struct MD5Sum< ::torobo_msgs::SetRobotControllerParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::SetRobotControllerParameter >::value();
  }
  static const char* value(const ::torobo_msgs::SetRobotControllerParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::SetRobotControllerParameterRequest> should match
// service_traits::DataType< ::torobo_msgs::SetRobotControllerParameter >
template<>
struct DataType< ::torobo_msgs::SetRobotControllerParameterRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::SetRobotControllerParameter >::value();
  }
  static const char* value(const ::torobo_msgs::SetRobotControllerParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::SetRobotControllerParameterResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::SetRobotControllerParameter >
template<>
struct MD5Sum< ::torobo_msgs::SetRobotControllerParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::SetRobotControllerParameter >::value();
  }
  static const char* value(const ::torobo_msgs::SetRobotControllerParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::SetRobotControllerParameterResponse> should match
// service_traits::DataType< ::torobo_msgs::SetRobotControllerParameter >
template<>
struct DataType< ::torobo_msgs::SetRobotControllerParameterResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::SetRobotControllerParameter >::value();
  }
  static const char* value(const ::torobo_msgs::SetRobotControllerParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_SETROBOTCONTROLLERPARAMETER_H
