// Generated by gencpp from file torobo_msgs/SetZeroEffort.msg
// DO NOT EDIT!


#ifndef TOROBO_MSGS_MESSAGE_SETZEROEFFORT_H
#define TOROBO_MSGS_MESSAGE_SETZEROEFFORT_H

#include <ros/service_traits.h>


#include <torobo_msgs/SetZeroEffortRequest.h>
#include <torobo_msgs/SetZeroEffortResponse.h>


namespace torobo_msgs
{

struct SetZeroEffort
{

typedef SetZeroEffortRequest Request;
typedef SetZeroEffortResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetZeroEffort
} // namespace torobo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::torobo_msgs::SetZeroEffort > {
  static const char* value()
  {
    return "abb91c83ed030d595b2e5754d356a7f3";
  }

  static const char* value(const ::torobo_msgs::SetZeroEffort&) { return value(); }
};

template<>
struct DataType< ::torobo_msgs::SetZeroEffort > {
  static const char* value()
  {
    return "torobo_msgs/SetZeroEffort";
  }

  static const char* value(const ::torobo_msgs::SetZeroEffort&) { return value(); }
};


// service_traits::MD5Sum< ::torobo_msgs::SetZeroEffortRequest> should match
// service_traits::MD5Sum< ::torobo_msgs::SetZeroEffort >
template<>
struct MD5Sum< ::torobo_msgs::SetZeroEffortRequest>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::SetZeroEffort >::value();
  }
  static const char* value(const ::torobo_msgs::SetZeroEffortRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::SetZeroEffortRequest> should match
// service_traits::DataType< ::torobo_msgs::SetZeroEffort >
template<>
struct DataType< ::torobo_msgs::SetZeroEffortRequest>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::SetZeroEffort >::value();
  }
  static const char* value(const ::torobo_msgs::SetZeroEffortRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::torobo_msgs::SetZeroEffortResponse> should match
// service_traits::MD5Sum< ::torobo_msgs::SetZeroEffort >
template<>
struct MD5Sum< ::torobo_msgs::SetZeroEffortResponse>
{
  static const char* value()
  {
    return MD5Sum< ::torobo_msgs::SetZeroEffort >::value();
  }
  static const char* value(const ::torobo_msgs::SetZeroEffortResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::torobo_msgs::SetZeroEffortResponse> should match
// service_traits::DataType< ::torobo_msgs::SetZeroEffort >
template<>
struct DataType< ::torobo_msgs::SetZeroEffortResponse>
{
  static const char* value()
  {
    return DataType< ::torobo_msgs::SetZeroEffort >::value();
  }
  static const char* value(const ::torobo_msgs::SetZeroEffortResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOROBO_MSGS_MESSAGE_SETZEROEFFORT_H
