(cl:in-package torobo_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIMESTAMP-VAL
          TIMESTAMP
          HOSTTIMESTAMP-VAL
          HOSTTIMESTAMP
          NAME-VAL
          NAME
          TYPE-VAL
          TYPE
          COMSTATUS-VAL
          COMSTATUS
          SYSTEMMODE-VAL
          SYSTEMMODE
          CTRLMODE-VAL
          CTRLMODE
          ERRORWARNINGSTATUS-VAL
          ERRORWARNINGSTATUS
          TRJSTATUS-VAL
          TRJSTATUS
          TRJVIAREMAIN-VAL
          TRJVIAREMAIN
          REFCURRENT-VAL
          REFCURRENT
          REFPOSITION-VAL
          REFPOSITION
          REFVELOCITY-VAL
          REFVELOCITY
          REFACCELERATION-VAL
          REFACCELERATION
          REFEFFORT-VAL
          REFEFFORT
          CURRENT-VAL
          CURRENT
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          OUTCONVINVELOCITY-VAL
          OUTCONVINVELOCITY
          ACCELERATION-VAL
          ACCELERATION
          OUTCONVINACCELERATION-VAL
          OUTCONVINACCELERATION
          EFFORT-VAL
          EFFORT
          TEMPERATURE-VAL
          TEMPERATURE
          GENERAL_0-VAL
          GENERAL_0
          GENERAL_1-VAL
          GENERAL_1
          GENERAL_2-VAL
          GENERAL_2
          GENERAL_3-VAL
          GENERAL_3
))