; Auto-generated. Do not edit!


(cl:in-package torobo_msgs-msg)


;//! \htmlinclude MoveHomePositionGoal.msg.html

(cl:defclass <MoveHomePositionGoal> (roslisp-msg-protocol:ros-message)
  ((transitionTime
    :reader transitionTime
    :initarg :transitionTime
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveHomePositionGoal (<MoveHomePositionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveHomePositionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveHomePositionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name torobo_msgs-msg:<MoveHomePositionGoal> is deprecated: use torobo_msgs-msg:MoveHomePositionGoal instead.")))

(cl:ensure-generic-function 'transitionTime-val :lambda-list '(m))
(cl:defmethod transitionTime-val ((m <MoveHomePositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader torobo_msgs-msg:transitionTime-val is deprecated.  Use torobo_msgs-msg:transitionTime instead.")
  (transitionTime m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveHomePositionGoal>) ostream)
  "Serializes a message object of type '<MoveHomePositionGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'transitionTime))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveHomePositionGoal>) istream)
  "Deserializes a message object of type '<MoveHomePositionGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'transitionTime) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveHomePositionGoal>)))
  "Returns string type for a message object of type '<MoveHomePositionGoal>"
  "torobo_msgs/MoveHomePositionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveHomePositionGoal)))
  "Returns string type for a message object of type 'MoveHomePositionGoal"
  "torobo_msgs/MoveHomePositionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveHomePositionGoal>)))
  "Returns md5sum for a message object of type '<MoveHomePositionGoal>"
  "71fd40116858649790e007be0d81d186")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveHomePositionGoal)))
  "Returns md5sum for a message object of type 'MoveHomePositionGoal"
  "71fd40116858649790e007be0d81d186")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveHomePositionGoal>)))
  "Returns full string definition for message of type '<MoveHomePositionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float64 transitionTime~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveHomePositionGoal)))
  "Returns full string definition for message of type 'MoveHomePositionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float64 transitionTime~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveHomePositionGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveHomePositionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveHomePositionGoal
    (cl:cons ':transitionTime (transitionTime msg))
))
